# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc1959ba1e713d88f7da4a69e45bbb5abe6fbe4b2decf3d5813565b51a2b477d38c4d5259dc3a0cde6fce84c5225c1f9f6f8596ca8601d876f9c6d69004e2a02

test:
  secret_key_base: 2eb633bdcf670f53f4e26b385f80235b377276adac0a8a5c6f8d3c601b77fe9f28b1316cb29e380b8e98d461bb71529b4cebc1e063e5144f4efe2ce6afc648a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
